data:
  store: 'json' # json, mongodb

  # only fill if store=mongodb
  mongodb: # mongodb connection
    uri: 'mongodb://localhost:27017'
    database: 'hmcrewards'

toasts:
  enabled: true

# configure the used sounds, the format is:
#    <type> [volume] [pitch]
# the type must be Minecraft's sound name, check
# a full list here: https://www.digminecraft.com/lists/sound_list_pc.php
# Also note that sounds are optional, you can just remove
# one and it will not play
sounds:
  # reward-give: 'entity.player.levelup 1 1'
  # reward-give-error: 'entity.villager.no 1 1'
  # reward-bulk-claim: 'entity.player.levelup 1 1'
  # reward-bulk-claim-error: 'entity.villager.no 1 1'

rewards:
  example_command:
    type: "command"

    # Required Inventory Slots for claiming
    required-space: 3

    # icon
    display:
      material: 'PAPER'
      custom-model-data: 3
      name: '<red>Example Command Reward'
      lore:
        - '<#d24c9f><bold>Contains:'
        - '<dark_gray>x1 <aqua>Diamond'
        - '<dark_gray>x1 <gold>Enchanted Golden Apple'
        - '<dark_gray>x1 <green>Emerald'

    # Commands to deliver to player
    commands:
      - 'say %player% claimed a command reward from HMCRewards!'
      - 'minecraft:give %player% minecraft:diamond 1'
      - 'minecraft:give %player% minecraft:enchanted_golden_apple 1'
      - 'minecraft:give %player% minecraft:emerald 1'