data:
  store: 'mongodb' # yaml, mongodb

  # only fill if store=mongodb
  mongodb: # mongodb connection
    uri: 'mongodb://localhost:27017'
    database: 'hmcrewards'

# configure the used sounds, the format is:
#    <type> [volume] [pitch]
# the type must be Minecraft's sound name, check
# a full list here: https://www.digminecraft.com/lists/sound_list_pc.php
# Also note that sounds are optional, you can just remove
# one and it will not play
sounds:
  # reward-give: 'entity.player.levelup 1 1'        (yusshu note: not sure if these sounds exists, copilot wrote them)
  # reward-give-error: 'entity.villager.no 1 1'
  # reward-bulk-claim: 'entity.player.levelup 1 1'
  # reward-bulk-claim-error: 'entity.villager.no 1 1'

#
# Commands to execute when a reward has been queued for a player
# Useful to notify them that they have new rewards
#
on-reward:
  - 'tell <player> You have new mail: <reward_display_name>'

rewards:
  command_1:
    type: "command"

    # Required Inventory Slots for claiming
    required-space: 3

    # icon
    display:
      material: 'oraxen:item_xyz'
      name: '<red>Command Reward'
      lore:
        - '<dark_gray>??????'

    # Commands to deliver to player
    commands:
      - 'mm i give %player% item_1'
      - 'mm i give %player% item_2'
      - 'mm i give %player% item_3'

  item_1:
    material: 'oraxen:item_xyz'
    name: '<red>Item Reward'
    lore:
      - '<dark_gray>??????'